controllers/ConselhoController.php
<?
namespace app\controllers;

use yii\web\Controller;
use yii\data\Pagination;
use app\models\ConselhoModel;
use app\models\CondominiosModel;
use Yii;

class ConselhoController extends Controller{
    public function actionListarConselheiros(){

        if(Yii::$app->user->isGuest){
            return $this->redirect(['site/login']);
        }

        $condTable = CondominiosModel::tableName();
        $conselhoTable = ConselhoModel::tableName();
        $query = (new \yii\db\Query())
            ->select(
                'conselho.id,
                cond.nome AS nomeCondo,
                conselho.nomeConselho,
                conselho.funcao,
                conselho.cpf,
                conselho.email,
                conselho.telefone,
                conselho.dataCadastro,
                conselho.dataModificado'
            )
            ->from($conselhoTable.' conselho')
            ->innerJoin($condTable.' cond', 'conselho.id_condominio = cond.id');

        $paginacao = new Pagination([
            'defaultPageSize' => 5,
            'totalCount' => $query->count()
        ]);

        $conselheiros = $query->orderBy('id')
            ->offset($paginacao->offset)
            ->limit($paginacao->limit)
            ->all();

        return $this->render('listar-conselheiros',[
            'conselheiros' => $conselheiros,
            'paginacao' => $paginacao
        ]);
    }

    public function actionCadastrarConselheiros(){
        
        if(Yii::$app->user->isGuest){
            return $this->redirect(['site/login']);
        }

        return $this->render('cadastrar-conselheiros');
    }

    public function actionRealizaCadastroConselheiro(){
        $request = \yii::$app->request;

        if($request->isPost){
            $model = new ConselhoModel();
            $model->attributes = $request->post();
            $model->cpf = str_replace('.','', $model->cpf);
            $model->cpf = str_replace('-','', $model->cpf);
            $model->telefone = str_replace('-','', $model->telefone);
            $model->telefone = str_replace('(','', $model->telefone);
            $model->telefone = str_replace(')','', $model->telefone);
            $model->telefone = str_replace(' ','', $model->telefone);
            $model->save();
            return $this->redirect(['conselho/listar-conselheiros']);
        }

        return $this->render('cadastrar-conselheiros');
    }

    public function actionEditarConselheiro(){
        $this->layout = false;
        $request = \yii::$app->request;
        if($request->isGet){
            $query = ConselhoModel::find();
            $conselho = $query->where(['id' => $request->get()])->one();
        }
      
        return $this->render('editar-conselheiro',[
            'edit' => $conselho
        ]);
    }

    public function actionRealizaEdicaoConselheiro(){
        $request = \yii::$app->request;
        if($request->isPost){
            $model = ConselhoModel::findOne($request->post('id'));
            $model->attributes = $request->post();
            $model->cpf = str_replace('.','', $model->cpf);
            $model->cpf = str_replace('-','', $model->cpf);
            $model->telefone = str_replace('-','', $model->telefone);
            $model->telefone = str_replace('(','', $model->telefone);
            $model->telefone = str_replace(')','', $model->telefone);
            $model->telefone = str_replace(' ','', $model->telefone);
            if($model->update()){
                return $this->redirect(['conselho/listar-conselheiros']);
            }else{
                return $this->redirect(['conselho/listar-conselheiros', 'msg' => 'erro']);
            }
        }
    }

    
    public function actionDeletaConselheiro(){
        $request = \yii::$app->request;

        if($request->isGet){
            $model = ConselhoModel::findOne($request->get('id'));
            if($model->delete()){
                return $this->redirect(['conselho/listar-conselheiros', 'myAlert'=>['type' => 'success', 'msg'=>'Registro deletado com sucesso.']]);
            }else{
                return $this->redirect(['conselho/listar-conselheiros','myAlert'=>['type' => 'danger','msg'=>'Registro não deletado.']]);
            }
        }
    }


}

?>

views/conselho/cadastrar-conselheiros.php
<?

use yii\helpers\Html;
use app\controllers\CondominiosController;
use app\controllers\ConselhoController;
use yii\helpers\Url;
$this->title = "Cadastrar Conselheiros";
?>
<h5>Cadastro de Conselho</h5>
    <form action="<?= Url::to(['conselho/realiza-cadastro-conselheiro']) ?>" method="post" class="mt-3 row formConselho mb-5">
        <div class="form-group col-md-6">
            <label for="condominio">Selecione o Condomínio</label>
            <select class="custom-select" name="id_condominio" id="id_condominio">
                <option value="">Condominio</option>
                <?php
                foreach (CondominiosController::listaCondominioSelect() as $opcaoCond) { ?>
                    <option value="<?= $opcaoCond['id'] ?>"><?= $opcaoCond['nome'] ?></option>
                <?php } ?>
            </select>
        </div>
        <div class="form-group col-md-6">
            <label for="funcao">Função</label>
            <select id="funcao" name="funcao" class="custom-select">
                <option value="Síndico">Síndico</option>
                <option value="Subsíndico">Subsíndico</option>
                <option value="Conselheiro">Conselheiro</option>
            </select>
        </div>
        <div class="form-group col-md-8">
            <label for="nomeConselho">Nome</label>
            <input type="text" class="form-control" id="nomeConselho" name="nomeConselho" value="" required>
        </div>
        <div class="form-group col-md-4">
            <label for="cpf">CPF</label>
            <input type="text" class="form-control" id="cpf" name="cpf" value="" required>
        </div>
        <div class="form-group col-md-8">
            <label for="email">Email</label>
            <input type="email" class="form-control" id="email" name="email" aria-describedby="emailHelp" value="" required>
        </div>
        <div class="form-group col-md-4">
            <label for="cpf">Telefone</label>
            <input type="text" class="form-control" id="telefone" name="telefone" value="">
        </div>
        <input type="hidden" name="<?= \yii::$app->request->csrfParam ?>" value="<?= \yii::$app->request->csrfToken ?>">
        <button type="submit" class="btn btn-dark buttonEnviar">Enviar</button>

</form>

views/conselho/editar-conselheiro.php
<?

use app\components\selectedComponent;
use yii\helpers\Html;
use app\controllers\CondominiosController;
use app\components\maskComponent;
use yii\helpers\Url;

$url_site = Url::base(true);
?>

<form action="<?= Url::to(['conselho/realiza-edicao-conselheiro']) ?>" method="post" class="col-12 mt-3 formConselho mb-5">
    <div class="form-group">
        <label for="condominio">Selecione o Condomínio</label>
        <select class="custom-select" name="id_condominio" id="id_condominio">
            <option value="">Condominio</option>
            <?php
            foreach (CondominiosController::listaCondominioSelect() as $opcaoCond) { ?>
                <option value="<?= $opcaoCond['id'] ?>" <?= selectedComponent::isSelected($opcaoCond['id'], $edit['id_condominio']) ?>><?= $opcaoCond['nome'] ?></option>
            <?php } ?>
        </select>
    </div>
    <div class="form-group">
        <label for="funcao">Função</label>
        <select id="funcao" name="funcao" class="custom-select">
            <option value="Síndico">Síndico</option>
            <option value="Subsíndico">Subsíndico</option>
            <option value="Conselheiro">Conselheiro</option>
        </select>
    </div>
    <div class="form-group">
        <label for="nomeConselho">Nome</label>
        <input type="text" class="form-control" id="nomeConselho" name="nomeConselho" value="<?= $edit['nomeConselho'] ?>" required>
    </div>
    <div class="form-group">
        <label for="cpf">CPF</label>
        <input type="text" class="form-control" id="cpf" name="cpf" value="<?= maskComponent::mask($edit['cpf'], 'cpf') ?>" required>
    </div>
    <div class="form-group">
        <label for="email">Email</label>
        <input type="email" class="form-control" id="email" name="email" aria-describedby="emailHelp" value="<?= $edit['email'] ?>" required>
    </div>
    <div class="form-group">
        <label for="cpf">Telefone</label>
        <input type="text" class="form-control" id="telefone" name="telefone" value="<?= maskComponent::mask($edit['telefone'], 'telefone') ?>">
    </div>
    <input type="hidden" name="<?= \yii::$app->request->csrfParam ?>" value="<?= \yii::$app->request->csrfToken ?>">
    <input type="hidden" name="id" value="<?= $edit['id'] ?>">
    <div class="row justify-content-between">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
        <button type="submit" class="btn btn-dark buttonEnviar">Enviar</button>
    </div>
</form>

views/conselho/listar-conselheiros.php
<?

use yii\widgets\LinkPager;
use yii\helpers\Url;
use app\components\modalComponent;
use app\components\alertComponent;
use app\components\maskComponent;

$url_site = Url::base(true);
$this->title = "Listar Conselheiros";
if(isset($_GET['myAlert'])){
    echo alertComponent::myAlert($_GET['myAlert']['type'],$_GET['myAlert']['msg']);
}
?>
<h1>Conselheiros</h1>
<div class="row">
    <table class="table col-12 table-responsive-lg mb-5 mt-5 tabelaConselho">
        <thead>
            <tr>
                <th scope="col">Condomínio</th>
                <th scope="col">Função</th>
                <th scope="col">Nome</th>
                <th scope="col">CPF</th>
                <th scope="col">E-mail</th>
                <th scope="col">Telefone</th>
                <th scope="col">Data Cad.</th>
                <th><a href="<?= $url_site ?>/index.php?r=conselho%2Fcadastrar-conselheiros"><button class="btn btn-dark">Adicionar</button></a></th>
            </tr>
        </thead>
        <tbody>
            <?php
            foreach ($conselheiros as $valor) {
            ?>
                <tr data-id="<?= $valor['id'] ?>" class="conselho">
                    <td><?=$valor['nomeCondo'] ?></td>
                    <td><?= $valor['funcao'] ?></td>
                    <td><?= $valor['nomeConselho'] ?></td>
                    <td><?= maskComponent::mask($valor['cpf'], 'cpf') ?></td>
                    <td><?= $valor['email'] ?></td>
                    <td><?= maskComponent::mask($valor['telefone'], 'telefone') ?></td>
                    <td><?= $valor['dataCadastro'] ?></td>
                    <td><a class="p-1 removerConselho" href="<?= $url_site ?>/index.php?r=conselho/deleta-conselheiro&id=<?= $valor['id'] ?>"><i class="bi bi-x-circle-fill text-danger"></i></a><a class="p-1 openModal" href="<?= $url_site ?>/index.php?r=conselho/editar-conselheiro&id=<?php echo $valor['id']; ?>"><i class="bi bi-pencil-square ml-1 text-info"></i></a></td>
                </tr>
    
            <?php } ?>
            <tr>
                <td colspan="7">&nbsp;</td>
                <td class="totalRegistros"><?php echo 'Registros: ' . ($paginacao->totalCount<10? '0'. $paginacao->totalCount : $paginacao->totalCount)?></td>
            </tr>
        </tbody>
    </table>
</div>

<?= LinkPager::widget(
    [
        'pagination' => $paginacao,
        'linkContainerOptions' => [
            'class' => 'btn-group'
        ],
        'linkOptions' => [
            'class' => 'btn btn-dark'
        ],
        'disabledListItemSubTagOptions' => [
            'class' => 'btn btn-secondary'
        ]
    ]
) ?>
    <?= modalComponent::initModal('Edição de Conselheiro'); ?>