controllers/BlocosController.php
<?
namespace app\controllers;

use yii\web\Controller;
use yii\data\Pagination;
use app\models\BlocosModel;
use app\models\CondominiosModel;
use Yii;

class BlocosController extends Controller{
    public function actionListarBlocos(){

        if(Yii::$app->user->isGuest){
            return $this->redirect(['site/login']);
        }

        $condTable = CondominiosModel::tableName();
        $blocoTable = BlocosModel::tableName();
        $query = (new \yii\db\Query())
            ->select(
                'bloco.id,
                bloco.id_condominio,
                cond.nome AS nomeCond,
                bloco.nome,
                bloco.numeroAndares,
                bloco.unidadesPAndar,
                bloco.dataCadastro,
                bloco.dataModificado'
            )
            ->from($blocoTable.' bloco')
            ->innerJoin($condTable.' cond', 'bloco.id_condominio = cond.id');
        //$query = BlocosModel::find();

        $paginacao = new Pagination([
            'defaultPageSize' => 5,
            'totalCount' => $query->count()
        ]);

        $blocos = $query->orderBy('nome')
            ->offset($paginacao->offset)
            ->limit($paginacao->limit)
            ->all();

        return $this->render('listar-blocos',[
            'blocos' => $blocos,
            'paginacao' => $paginacao
        ]);
    }

    public static function listaBlocoSelect(){
        $query = BlocosModel::find();

        return $query->orderBy('nome')->all();
    }

    public static function listaBlocoEditar($id_condominio){
        $query = BlocosModel::find();
        $data = $query->where(['id_condominio' =>$id_condominio])->orderBy('nome')->all();
        return $data;
    }

    public function actionListaBlocoApi(){
        $request = \yii::$app->request;
        $query = BlocosModel::find();
        $data = $query->where(['id_condominio' => $request->post()])->orderBy('nome')->all();

        $dados = array();
        $i = 0;
        foreach($data as $d){
            $dados[$i]['id'] = $d['id'];
            $dados[$i]['nome'] = $d['nome'];
            $i++;
        }
        return json_encode($dados);
    }

    public function actionCadastrarBlocos(){

        if(Yii::$app->user->isGuest){
            return $this->redirect(['site/login']);
        }
        
        return $this->render('cadastrar-blocos');
    }

    public function actionRealizaCadastroBloco(){
        $request = \yii::$app->request;

        if($request->isPost){
            $model = new BlocosModel();
            $model->attributes = $request->post();
            $model->save();
            return $this->redirect(['blocos/listar-blocos']);
        }

        return $this->render('cadastrar-blocos');
    }

    public function actionEditarBloco(){
        $this->layout = false;
        $request = \yii::$app->request;
        if($request->isGet){
            $query = BlocosModel::find();
            $blocos = $query->where(['id' => $request->get()])->one();
        }
      
        return $this->render('editar-bloco',[
            'edit' => $blocos
        ]);
    }

    public function actionRealizaEdicaoBloco(){
        $request = \yii::$app->request;
        if($request->isPost){
            $model = BlocosModel::findOne($request->post('id'));
            $model->attributes = $request->post();
            if($model->update()){
                return $this->redirect(['blocos/listar-blocos']);
            }else{
                return $this->redirect(['blocos/listar-blocos', 'msg' => 'erro']);
            }
        }
    }

    public function actionDeletaBloco(){
        $request = \yii::$app->request;

        if($request->isGet){
            $model = BlocosModel::findOne($request->get('id'));
            if($model->delete()){
                return $this->redirect(['blocos/listar-blocos', 'myAlert'=>['type' => 'success', 'msg'=>'Registro deletado com sucesso.']]);
            }else{
                return $this->redirect(['blocos/listar-blocos','myAlert'=>['type' => 'danger','msg'=>'Registro não deletado.']]);
            }
        }
    }

    
}


?>

controllers/ConselhoController.php
<?
namespace app\controllers;

use yii\web\Controller;
use yii\data\Pagination;
use app\models\ConselhoModel;
use app\models\CondominiosModel;
use Yii;

class ConselhoController extends Controller{
    public function actionListarConselheiros(){

        if(Yii::$app->user->isGuest){
            return $this->redirect(['site/login']);
        }

        $condTable = CondominiosModel::tableName();
        $conselhoTable = ConselhoModel::tableName();
        $query = (new \yii\db\Query())
            ->select(
                'conselho.id,
                cond.nome AS nomeCondo,
                conselho.nomeConselho,
                conselho.funcao,
                conselho.cpf,
                conselho.email,
                conselho.telefone,
                conselho.dataCadastro,
                conselho.dataModificado'
            )
            ->from($conselhoTable.' conselho')
            ->innerJoin($condTable.' cond', 'conselho.id_condominio = cond.id');

        $paginacao = new Pagination([
            'defaultPageSize' => 5,
            'totalCount' => $query->count()
        ]);

        $conselheiros = $query->orderBy('id')
            ->offset($paginacao->offset)
            ->limit($paginacao->limit)
            ->all();

        return $this->render('listar-conselheiros',[
            'conselheiros' => $conselheiros,
            'paginacao' => $paginacao
        ]);
    }

    public function actionCadastrarConselheiros(){
        
        if(Yii::$app->user->isGuest){
            return $this->redirect(['site/login']);
        }

        return $this->render('cadastrar-conselheiros');
    }

    public function actionRealizaCadastroConselheiro(){
        $request = \yii::$app->request;

        if($request->isPost){
            $model = new ConselhoModel();
            $model->attributes = $request->post();
            $model->cpf = str_replace('.','', $model->cpf);
            $model->cpf = str_replace('-','', $model->cpf);
            $model->telefone = str_replace('-','', $model->telefone);
            $model->telefone = str_replace('(','', $model->telefone);
            $model->telefone = str_replace(')','', $model->telefone);
            $model->telefone = str_replace(' ','', $model->telefone);
            $model->save();
            return $this->redirect(['conselho/listar-conselheiros']);
        }

        return $this->render('cadastrar-conselheiros');
    }

    public function actionEditarConselheiro(){
        $this->layout = false;
        $request = \yii::$app->request;
        if($request->isGet){
            $query = ConselhoModel::find();
            $conselho = $query->where(['id' => $request->get()])->one();
        }
      
        return $this->render('editar-conselheiro',[
            'edit' => $conselho
        ]);
    }

    public function actionRealizaEdicaoConselheiro(){
        $request = \yii::$app->request;
        if($request->isPost){
            $model = ConselhoModel::findOne($request->post('id'));
            $model->attributes = $request->post();
            $model->cpf = str_replace('.','', $model->cpf);
            $model->cpf = str_replace('-','', $model->cpf);
            $model->telefone = str_replace('-','', $model->telefone);
            $model->telefone = str_replace('(','', $model->telefone);
            $model->telefone = str_replace(')','', $model->telefone);
            $model->telefone = str_replace(' ','', $model->telefone);
            if($model->update()){
                return $this->redirect(['conselho/listar-conselheiros']);
            }else{
                return $this->redirect(['conselho/listar-conselheiros', 'msg' => 'erro']);
            }
        }
    }

    
    public function actionDeletaConselheiro(){
        $request = \yii::$app->request;

        if($request->isGet){
            $model = ConselhoModel::findOne($request->get('id'));
            if($model->delete()){
                return $this->redirect(['conselho/listar-conselheiros', 'myAlert'=>['type' => 'success', 'msg'=>'Registro deletado com sucesso.']]);
            }else{
                return $this->redirect(['conselho/listar-conselheiros','myAlert'=>['type' => 'danger','msg'=>'Registro não deletado.']]);
            }
        }
    }


}

?>

controllers/UnidadesController.php
<?
namespace app\controllers;

use yii\web\Controller;
use yii\data\Pagination;
use app\models\UnidadesModel;
use app\models\BlocosModel;
use app\models\CondominiosModel;
use Yii;

class UnidadesController extends Controller{
    public function actionListarUnidades(){

        if(Yii::$app->user->isGuest){
            return $this->redirect(['site/login']);
        }

        $condTable = CondominiosModel::tableName();
        $blocoTable = BlocosModel::tableName();
        $unidadesTable = UnidadesModel::tableName();
        $query = (new \yii\db\Query())
            ->select(
                'unidade.id,
                unidade.id_bloco,
                bloco.nome AS nomeBloco,
                cond.nome AS nomeCondo,
                unidade.numeroUnidade,
                unidade.metragem,
                unidade.vagasDeGaragem,
                unidade.dataCadastro,
                unidade.dataModificado'
            )
            ->from($unidadesTable.' unidade')
            ->innerJoin($condTable.' cond', 'unidade.id_condominio = cond.id')
            ->innerJoin($blocoTable.' bloco', 'unidade.id_bloco = bloco.id');
        //$query = UnidadesModel::find();

        $paginacao = new Pagination([
            'defaultPageSize' => 5,
            'totalCount' => $query->count()
        ]);

        $unidades = $query->orderBy('numeroUnidade')
            ->offset($paginacao->offset)
            ->limit($paginacao->limit)
            ->all();

        return $this->render('listar-unidades',[
            'unidades' => $unidades,
            'paginacao' => $paginacao
        ]);
    }

    public static function listaUnidadeSelect(){
        $query = UnidadesModel::find();

        return $query->orderBy('numeroUnidade')->all();
    }

    public static function listaUnidadeEditar($id_bloco){
        
        $query = UnidadesModel::find();
        $data = $query->where(['id_bloco' => $id_bloco])->orderBy('numeroUnidade')->all();
        return $data;
    }

    public function actionCadastrarUnidades(){

        if(Yii::$app->user->isGuest){
            return $this->redirect(['site/login']);
        }

        return $this->render('cadastrar-unidades');
    }

    public function actionListaUnidadeApi(){
        $request = \yii::$app->request;
        $query = UnidadesModel::find();
        $data = $query->where(['id_bloco' => $request->post()])->orderBy('numeroUnidade')->all();

        $dados = array();
        $i = 0;
        foreach($data as $d){
            $dados[$i]['id'] = $d['id'];
            $dados[$i]['numeroUnidade'] = $d['numeroUnidade'];
            $i++;
        }
        return json_encode($dados);
    }

    public function actionRealizaCadastroUnidade(){
        $request = \yii::$app->request;

        if($request->isPost){
            $model = new UnidadesModel();
            $model->attributes = $request->post();
            $model->save();
            return $this->redirect(['unidades/listar-unidades']);
        }
        return $this->render('cadastrar-condominios');
    }

    public function actionEditarUnidade(){
        $this->layout = false;
        $request = \yii::$app->request;
        if($request->isGet){
            $query = UnidadesModel::find();
            $unidades = $query->where(['id' => $request->get()])->one();
        }        
        
        return $this->render('editar-unidade',[
            'edit' => $unidades
        ]);
    }

    public function actionRealizaEdicaoUnidade(){
        $request = \yii::$app->request;
        if($request->isPost){
            $model = UnidadesModel::findOne($request->post('id'));
            $model->attributes = $request->post();
            if($model->update()){
                return $this->redirect(['unidades/listar-unidades']);
            }else{
                return $this->redirect(['unidades/listar-unidades', 'msg' => 'erro']);
            }
        }
    }

    public function actionDeletaUnidade(){
        $request = \yii::$app->request;

        if($request->isGet){
            $model = UnidadesModel::findOne($request->get('id'));
            if($model->delete()){
                return $this->redirect(['unidades/listar-unidades', 'myAlert'=>['type' => 'success', 'msg'=>'Registro deletado com sucesso.']]);
            }else{
                return $this->redirect(['unidades/listar-unidades','myAlert'=>['type' => 'danger','msg'=>'Registro não deletado.']]);
            }
        }
    }

}

?>

controllers/UsuariosController.php
<?

namespace app\controllers;

use yii\web\Controller;
use yii\data\Pagination;
use app\models\User;
use Yii;

class UsuariosController extends Controller{
    public function actionListarUsuarios(){
 
        if(Yii::$app->user->isGuest){
            return $this->redirect(['site/login']);
        }

        $query = User::find();

        $paginacao = new Pagination([
            'defaultPageSize' => 5,
            'totalCount' => $query->count(),
        ]);

        $usuarios = $query->orderBy('nome')
            ->offset($paginacao->offset)
            ->limit($paginacao->limit)
            ->all();

        return $this->render('listar-usuarios',[
            'usuarios' => $usuarios,
            'paginacao' =>$paginacao,
        ]);
    }

    public function actionCadastrarUsuarios(){
        
        if(Yii::$app->user->isGuest){
            return $this->redirect(['site/login']);
        }

        return $this->render('cadastrar-usuarios');

    }

    public function actionRealizaCadastroUsuario(){
        $request = \yii::$app->request;

        if($request->isPost){
            $model = new User();
            $model->attributes = $request->post();
            $model->save();
            return $this->redirect(['usuarios/listar-usuarios']);
        }

        return $this->render('cadastrar-usuarios');
    }

    public function actionEditarUsuario(){
        $this->layout = false;
        $request = \yii::$app->request;
        if($request->isGet){
            $query = User::find();
            $usuarios = $query->where(['id' => $request->get()])->one();
        }
      
        return $this->render('editar-usuario',[
            'edit' => $usuarios
        ]);
    }

    public function actionRealizaEdicaoUsuario(){
        $request = \yii::$app->request;
        if($request->isPost){
            $model = User::findOne($request->post('id'));
            $model->attributes = $request->post();
            if($model->update()){
                return $this->redirect(['usuarios/listar-usuarios']);
            }else{
                return $this->redirect(['usuarios/listar-usuarios', 'msg' => 'erro']);
            }
        }
    }

    public function actionDeletaUsuario(){
        $request = \yii::$app->request;
        if($request->isGet){
            $model = User::findOne($request->get('id'));
            if($model->delete()){
                return $this->redirect(['usuarios/listar-usuarios', 'myAlert'=>['type' => 'success', 'msg'=>'Registro deletado com sucesso.']]);
            }else{
                return $this->redirect(['usuarios/listar-usuarios','myAlert'=>['type' => 'danger','msg'=>'Registro não deletado.']]);
            }
        }
    }


}

?>

views/layouts/main.php
<?php

/** @var yii\web\View $this */
/** @var string $content */

use app\assets\AppAsset;
use app\widgets\Alert;
use yii\bootstrap4\Breadcrumbs;
use yii\bootstrap4\Html;
use yii\bootstrap4\Nav;
use yii\bootstrap4\NavBar;
use kartik\icons\FontAwesomeAsset;

FontAwesomeAsset::register($this);

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="pt-BR" class="h-100">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
    <?php $this->head() ?>
</head>
<body class="d-flex flex-column h-100">
<?php $this->beginBody() ?>

<header>
    <?php
    NavBar::begin([
        'brandLabel' => '<img src="img/logo.png" width="100px"/>',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar navbar-expand-xl navbar-dark bg-dark fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav text-white'],
        'items' => [
            [
                'label' => 'Home',
                'url' => ['site/index']
            ],
            [
                'label' => 'Administradoras',
                'items' => [
                    [
                        'label' => 'Listar',
                        'url' => ['administradoras/listar-administradoras']
                    ],[
                        'label' =>'Cadastrar',
                        'url' =>['administradoras/cadastrar-administradoras']
                    ]

                    ]
            ],
            [
                'label' => 'Condominios',
                'items' => [
                    [
                        'label' => 'Listar',
                        'url' => ['condominios/listar-condominios']
                    ],[
                        'label' =>'Cadastrar',
                        'url' =>['condominios/cadastrar-condominios']
                    ]

                    ]
            ],
            [
                'label' => 'Blocos',
                'items' => [
                    [
                        'label' => 'Listar',
                        'url' => ['blocos/listar-blocos']
                    ],[
                        'label' =>'Cadastrar',
                        'url' =>['blocos/cadastrar-blocos']
                    ]

                    ]
            ],
            [
                'label' => 'Unidades',
                'items' => [
                    [
                        'label' => 'Listar',
                        'url' => ['unidades/listar-unidades']
                    ],[
                        'label' =>'Cadastrar',
                        'url' =>['unidades/cadastrar-unidades']
                    ]

                    ]
            ],
            [
                'label' => 'Moradores',
                'items' => [
                    [
                        'label' => 'Listar',
                        'url' => ['moradores/listar-moradores']
                    ],[
                        'label' =>'Cadastrar',
                        'url' =>['moradores/cadastrar-moradores']
                    ]

                    ]
            ],
            [
                'label' => 'Conselho',
                'items' => [
                    [
                        'label' => 'Listar',
                        'url' => ['conselho/listar-conselheiros']
                    ],[
                        'label' =>'Cadastrar',
                        'url' =>['conselho/cadastrar-conselheiros']
                    ]

                    ]
            ],
            [
                'label' => 'Usuários',
                'items' => [
                    [
                        'label' => 'Listar',
                        'url' => ['usuarios/listar-usuarios']
                    ],[
                        'label' =>'Cadastrar',
                        'url' =>['usuarios/cadastrar-usuarios']
                    ]

                    ]
            ],
            Yii::$app->user->isGuest ? (
                ['label' => 'Login', 'url' => ['/site/login']]
            ) : (
                '<li>'
                . Html::beginForm(['/site/logout'],'post',['class' => 'form-inline'])
                . Html::submitButton(
                    'Logout ('. Yii::$app->user->identity->usuario.')',
                    ['class' => 'btn btn-link logout']
                )
                . Html::endForm()
                . '</li>'
            )
        ],
    ]);
    NavBar::end();
    ?>
</header>

<main role="main" class="flex-shrink-0 mt-5">
    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</main>

<footer class="footer mt-auto py-3 text-white bg-dark">
    <div class="container">
        <p class="float-left">&copy; AP Coders <?= date('Y') ?></p>
        <p class="float-right">Powered by Reginaldo</p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>