controllers/CondominiosController.php
<?

namespace app\controllers;

use app\models\AdministradorasModel;
use yii\web\Controller;
use yii\data\Pagination;
use app\models\CondominiosModel;
use app\controllers\userLogadoController;
use Yii;

class CondominiosController extends Controller{
    
    public function actionListarCondominios(){

        if(Yii::$app->user->isGuest){
            return $this->redirect(['site/login']);
        }

        $condTable = CondominiosModel::tableName();
        $admTable = AdministradorasModel::tableName();
        // $query = CondominiosModel::find();
        $query = (new \yii\db\Query())
            ->select(
                'cond.id,
                cond.id_administradora, 
                adm.nome AS admNome,
                cond.nome,
                cond.qtBlocos,
                cond.cep,
                cond.logradouro,
                cond.numero,
                cond.bairro,
                cond.cidade,
                cond.estado,
                cond.dataCadastro,
                cond.dataModificado'
            )
            ->from($condTable.' cond')
            ->innerJoin($admTable.' adm', 'adm.id = cond.id_administradora');

        $paginacao = new Pagination([
            'defaultPageSize' => 5,
            'totalCount' => $query->count(),
        ]);

        $condominios = $query->orderBy('cond.nome')
            ->offset($paginacao->offset)
            ->limit($paginacao->limit)
            ->all();

        return $this->render('listar-condominios',[
            'condominios' => $condominios,
            'paginacao' =>$paginacao,
        ]);
    }

    public static function listaCondominioSelect(){
        $query = CondominiosModel::find();

        return $query->orderBy('nome')->all();
    }

    public function actionCadastrarCondominios(){
        
        if(Yii::$app->user->isGuest){
            return $this->redirect(['site/login']);
        }

        return $this->render('cadastrar-condominios');

    }

    public function actionRealizaCadastroCondominio(){
        $request = \yii::$app->request;

        if($request->isPost){
            $model = new CondominiosModel();
            $model->attributes = $request->post();
            $model->cep = str_replace('-','', $model->cep);
            $model->save();
            return $this->redirect(['condominios/listar-condominios']);
        }

        return $this->render('cadastrar-condominios');
    }

    public function actionEditarCondominio(){
        $this->layout = false;
        $request = \yii::$app->request;
        if($request->isGet){
            $query = CondominiosModel::find();
            $condominios = $query->where(['id' => $request->get()])->one();
        }
      
        return $this->render('editar-condominio',[
            'edit' => $condominios
        ]);
    }

    public function actionRealizaEdicaoCondominio(){
        $request = \yii::$app->request;
        if($request->isPost){
            $model = CondominiosModel::findOne($request->post('id'));
            $model->attributes = $request->post();
            $model->cep = str_replace('-','', $model->cep);
            if($model->update()){
                return $this->redirect(['condominios/listar-condominios']);
            }else{
                return $this->redirect(['condominios/listar-condominios', 'msg' => 'erro']);
            }
        }
    }

    public function actionDeletaCondominio(){
        $request = \yii::$app->request;

        if($request->isGet){
            $model = CondominiosModel::findOne($request->get('id'));
            if($model->delete()){
                return $this->redirect(['condominios/listar-condominios', 'myAlert'=>['type' => 'success', 'msg'=>'Registro deletado com sucesso.']]);
            }else{
                return $this->redirect(['condominios/listar-condominios','myAlert'=>['type' => 'danger','msg'=>'Registro não deletado.']]);
            }
        }
    }

}

?>

views/condominios/cadastrar-condominios.php
<?

use yii\helpers\Url;
use app\controllers\AdministradorasController;
use app\components\estadosComponent;

$this->title = "Cadastrar Condomínios";
?>
<h5>Cadastro de Condomínio</h5>
<form action="<?= Url::to(['condominios/realiza-cadastro-condominio']); ?>" method="post" class="col-12 mt-3 formCondominio">
    <div class="row">
        <div class="form-group col-lg-8">
            <label for="nomeCondominio">Nome Condomínio</label>
            <input type="text" class="form-control" id="nome" name="nome" value="" required>
        </div>
        <div class="form-group col-md-6 col-lg-4">
            <label for="qtBlocos">Quantidade de Blocos</label>
            <input type="text" class="form-control" id="qtBlocos" name="qtBlocos" value="" required>
        </div>
        <div class="form-group col-md-6 col-lg-4">
            <label for="cep">CEP</label>
            <input type="text" class="form-control" id="cep" name="cep" value="" required>
        </div>
        <div class="form-group col-md-8 col-lg-8">
            <label for="logradouro">Logradouro</label>
            <input type="text" class="form-control" id="rua" name="logradouro" value="" required>
        </div>
        <div class="form-group col-md-4 col-lg-2">
            <label for="numero">Número</label>
            <input type="text" class="form-control" id="numero" name="numero" value="" required>
        </div>
        <div class="form-group col-lg-5">
            <label for="bairro">Bairro</label>
            <input type="text" class="form-control" id="bairro" name="bairro" value="" required>
        </div>
        <div class="form-group col-lg-5">
            <label for="cidade">Cidade</label>
            <input type="text" class="form-control" id="cidade" name="cidade" value="" required>
        </div>
        <div class="form-group col-lg-6">
            <label for="estado">Estado</label>
            <select class="custom-select" name="estado" id="uf">
                <option value="">Estado</option>
                <?
                foreach (estadosComponent::estadosSiglas() as $sig => $uf) { ?>
                    <option value="<?= $sig ?>"><?= $uf ?></option>
                <? } ?>

            </select>
        </div>
        <div class="form-group col-lg-6">
            <label for="id_administradora">Administradora Responsável</label>
            <select class="custom-select" name="id_administradora" id="id_administradora" required>
                <option value="">Administradora</option>
                <?php
                foreach (AdministradorasController::listaAdministradoraSelect() as $adm) { ?>
                    <option value="<?= $adm['id'] ?>"><?= $adm['nome'] ?></option>
                <?php  } ?>
            </select>
            <input type="hidden" name="<?= \yii::$app->request->csrfParam ?>" value="<?= \yii::$app->request->csrfToken ?>">
        </div>
    </div>
    <button type="submit" class="btn btn-dark buttonEnviar">Enviar</button>
</form>

views/condominios/editar-condominio.php
<?

use app\components\selectedComponent;
use app\components\maskComponent;
use yii\helpers\Url;
use app\controllers\AdministradorasController;
use app\components\estadosComponent;

?>
<form action="<?= Url::to(['condominios/realiza-edicao-condominio']); ?>" method="post" class="col-12 mt-3 formCondominio">
    <div class="container">
        <div class="row">

            
            <div class="form-group col-lg-8">
                <label for="nomeCondominio">Nome Condomínio</label>
                <input type="text" class="form-control" id="nome" name="nome" value="<?= $edit['nome'] ?>" required>
            </div>
            <div class="form-group col-md-6 col-lg-4">
                <label for="qtBlocos">Quantidade de Blocos</label>
                <input type="text" class="form-control" id="qtBlocos" name="qtBlocos" value="<?= $edit['qtBlocos'] ?>" required>
            </div>
            <div class="form-group col-md-6 col-lg-4">
                <label for="cep">CEP</label>
                <input type="text" class="form-control" id="cep" name="cep" value="<?= maskComponent::mask($edit['cep'], 'cep') ?>">
            </div>
            <div class="form-group col-md-8 col-lg-8">
                <label for="logradouro">Logradouro</label>
                <input type="text" class="form-control" id="rua" name="logradouro" value="<?= $edit['logradouro'] ?>" required>
            </div>
            <div class="form-group col-md-4 col-lg-2">
                <label for="numero">Número</label>
                <input type="text" class="form-control" id="numero" name="numero" value="<?= $edit['numero'] ?>">
            </div>
            <div class="form-group col-lg-5">
                <label for="bairro">Bairro</label>
                <input type="text" class="form-control" id="bairro" name="bairro" value="<?= $edit['bairro'] ?>">
            </div>
            <div class="form-group col-lg-5">
                <label for="cidade">Cidade</label>
                <input type="text" class="form-control" id="cidade" name="cidade" value="<?= $edit['cidade'] ?>">
            </div>
            <div class="form-group col-lg-6">
                <label for="estado">Estado</label>
                <select class="custom-select" name="estado" id="estado">
                    <option value="">Estado</option>
                    <?
                    foreach (estadosComponent::estadosSiglas() as $sig => $uf) { ?>
                        <option value="<?= $sig ?>" <?= selectedComponent::isSelected($sig, $edit['estado']) ?>><?= $uf ?></option>
                    <? } ?>
                </select>
            </div>
            <div class="form-group col-lg-6">
                <label for="id_administradora">Administradora Responsável</label>
                <select class="custom-select" name="id_administradora" id="id_administradora">
                    <option value="">Administradora</option>
                    <?php
                    foreach (AdministradorasController::listaAdministradoraSelect() as $adm) { ?>
                        <option value="<?= $adm['id'] ?>" <?= selectedComponent::isSelected($adm['id'], $edit['id_administradora']) ?>><?= $adm['nome'] ?></option>
                    <?php  } ?>
                </select>
            </div>
        
            <input type="hidden" name="<?= \yii::$app->request->csrfParam ?>" value="<?= \yii::$app->request->csrfToken ?>">
            <input type="hidden" name="id" value="<?= $edit['id'] ?>">
        </div>
        <div class="row justify-content-between">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
            <button type="submit" class="btn btn-dark buttonEnviar">Enviar</button>
        </div>
    </div>
</form>

views/condominios/listar-condominios.php
<?
use app\components\modalComponent;
use app\components\maskComponent;
use yii\helpers\Html;
use yii\widgets\LinkPager;
use yii\helpers\Url;
use app\components\alertComponent;

$url_site = Url::base(true);
$this->title = "Listar Condomínios";
if(isset($_GET['myAlert'])){
    echo alertComponent::myAlert($_GET['myAlert']['type'],$_GET['myAlert']['msg']);
}
?>
<h1>Condomínios</h1>
<div class="row">

    <table class="table col-12 table-responsive mb-5 mt-5 tabelaCondominios">
        <thead>
            <tr>
                <th scope="col">Nome</th>
                <th scope="col">Qt. Blocos</th>
                <th scope="col">Endereço</th>
                <th scope="col">Administradora</th>
                <th scope="col">Data Cad.</th>
                <th><a href="<?= $url_site ?>/index.php?r=condominios%2Fcadastrar-condominios"><button class="btn btn-dark">Adicionar</button></a></th>
            </tr>
        </thead>
        <tbody>
            <?php 
            foreach($condominios as $condo){ 
            ?>
                <tr data-id="<?= $condo['id']; ?>" class="condominio">
                    <td><?= $condo['nome'] ?></td>
                    <td><?= $condo['qtBlocos'] ?></td>
                    <td><?= $condo['logradouro'].', '.$condo['numero'].', '.$condo['bairro'].', '.$condo['cidade'].', '.$condo['estado'].', CEP '. maskComponent::mask($condo['cep'],'cep') ?></td>
                    <td><?= $condo['admNome'] ?></td>
                    <td><?= Yii::$app->formatter->format($condo['dataCadastro'], 'date') ?></td>
                    <td><a class="p-1 removerCondominio" href="<?= $url_site ?>/index.php?r=condominios/deleta-condominio&id=<?= $condo['id']; ?>"><i class="bi bi-x-circle-fill text-danger"></i></a><a class="p-1 openModal" href="<?= $url_site ?>/index.php?r=condominios/editar-condominio&id=<?= $condo['id']; ?>"><i class="bi bi-pencil-square ml-1 text-info"></i></a></td>
                </tr>
    
            <?php } ?> 
            <tr>
                <td colspan="5">&nbsp;</td>
                <td class="totalRegistros"><?php echo 'Registros: ' . ($paginacao->totalCount<10? '0'. $paginacao->totalCount : $paginacao->totalCount)?></td>
            </tr>
        </tbody>
    </table>
</div>

<?= LinkPager::widget(
    [
        'pagination' => $paginacao,
        'linkContainerOptions' => [
            'class' => 'btn-group'
        ],
        'linkOptions' => [
            'class' => 'btn btn-dark'
        ],
        'disabledListItemSubTagOptions' => [
            'class' => 'btn btn-secondary'
        ]
    ]
    ) ?>
<?= modalComponent::initModal('Edição de Condomínio') ?>