controllers/BlocosController.php
<?
namespace app\controllers;

use yii\web\Controller;
use yii\data\Pagination;
use app\models\BlocosModel;
use app\models\CondominiosModel;
use Yii;

class BlocosController extends Controller{
    public function actionListarBlocos(){

        if(Yii::$app->user->isGuest){
            return $this->redirect(['site/login']);
        }

        $condTable = CondominiosModel::tableName();
        $blocoTable = BlocosModel::tableName();
        $query = (new \yii\db\Query())
            ->select(
                'bloco.id,
                bloco.id_condominio,
                cond.nome AS nomeCond,
                bloco.nome,
                bloco.numeroAndares,
                bloco.unidadesPAndar,
                bloco.dataCadastro,
                bloco.dataModificado'
            )
            ->from($blocoTable.' bloco')
            ->innerJoin($condTable.' cond', 'bloco.id_condominio = cond.id');
        //$query = BlocosModel::find();

        $paginacao = new Pagination([
            'defaultPageSize' => 5,
            'totalCount' => $query->count()
        ]);

        $blocos = $query->orderBy('nome')
            ->offset($paginacao->offset)
            ->limit($paginacao->limit)
            ->all();

        return $this->render('listar-blocos',[
            'blocos' => $blocos,
            'paginacao' => $paginacao
        ]);
    }

    public static function listaBlocoSelect(){
        $query = BlocosModel::find();

        return $query->orderBy('nome')->all();
    }

    public static function listaBlocoEditar($id_condominio){
        $query = BlocosModel::find();
        $data = $query->where(['id_condominio' =>$id_condominio])->orderBy('nome')->all();
        return $data;
    }

    public function actionListaBlocoApi(){
        $request = \yii::$app->request;
        $query = BlocosModel::find();
        $data = $query->where(['id_condominio' => $request->post()])->orderBy('nome')->all();

        $dados = array();
        $i = 0;
        foreach($data as $d){
            $dados[$i]['id'] = $d['id'];
            $dados[$i]['nome'] = $d['nome'];
            $i++;
        }
        return json_encode($dados);
    }

    public function actionCadastrarBlocos(){

        if(Yii::$app->user->isGuest){
            return $this->redirect(['site/login']);
        }
        
        return $this->render('cadastrar-blocos');
    }

    public function actionRealizaCadastroBloco(){
        $request = \yii::$app->request;

        if($request->isPost){
            $model = new BlocosModel();
            $model->attributes = $request->post();
            $model->save();
            return $this->redirect(['blocos/listar-blocos']);
        }

        return $this->render('cadastrar-blocos');
    }

    public function actionEditarBloco(){
        $this->layout = false;
        $request = \yii::$app->request;
        if($request->isGet){
            $query = BlocosModel::find();
            $blocos = $query->where(['id' => $request->get()])->one();
        }
      
        return $this->render('editar-bloco',[
            'edit' => $blocos
        ]);
    }

    public function actionRealizaEdicaoBloco(){
        $request = \yii::$app->request;
        if($request->isPost){
            $model = BlocosModel::findOne($request->post('id'));
            $model->attributes = $request->post();
            if($model->update()){
                return $this->redirect(['blocos/listar-blocos']);
            }else{
                return $this->redirect(['blocos/listar-blocos', 'msg' => 'erro']);
            }
        }
    }

    public function actionDeletaBloco(){
        $request = \yii::$app->request;

        if($request->isGet){
            $model = BlocosModel::findOne($request->get('id'));
            if($model->delete()){
                return $this->redirect(['blocos/listar-blocos', 'myAlert'=>['type' => 'success', 'msg'=>'Registro deletado com sucesso.']]);
            }else{
                return $this->redirect(['blocos/listar-blocos','myAlert'=>['type' => 'danger','msg'=>'Registro não deletado.']]);
            }
        }
    }

    
}


?>

views/blocos/cadastrar-blocos.php
<?
use yii\helpers\Html;
use yii\helpers\Url;
use app\controllers\CondominiosController;
$this->title = "Cadastrar Blocos";
?>

<h5>Cadastro de Bloco</h5>
    <form action="<?= Url::to(['blocos/realiza-cadastro-bloco']) ?>" method="post" class="col-12 mt-3 formBloco">
        <div class="form-group">
            <label for="condominio">Condomínio</label>
            <select class="custom-select" name="id_condominio">
                <option value="">Condominio</option>
                <?php 
                foreach(CondominiosController::listaCondominioSelect() as $opcaoCond){ ?>
                        <option value="<?= $opcaoCond['id'] ?>"><?= $opcaoCond['nome'] ?></option>
                <?php } ?>
            </select>
        </div>
        <div class="form-group">
            <label for="nomeBloco">Nome do Bloco</label>
            <input type="text" class="form-control" id="nome" name="nome" value="" required>
        </div>
        <div class="form-group">
            <label for="numeroAndares">Número de Andares</label>
            <input type="text" class="form-control" id="numeroAndares" name="numeroAndares" value="" required>
        </div>
        <div class="form-group">
            <label for="unidadesPAndar">Unidades por Andar</label>
            <input type="text" class="form-control" id="unidadesPAndar" name="unidadesPAndar" value="" required>
        </div>

        <input type="hidden" name="<?= \yii::$app->request->csrfParam ?>" value="<?= \yii::$app->request->csrfToken ?>">

            <button type="submit" class="btn btn-dark buttonEnviar">Enviar</button>
    </form>

views/blocos/editar-bloco.php
<?

use app\components\selectedComponent;
use yii\helpers\Url;
use app\controllers\CondominiosController;
?>

<form action="<?= Url::to(['blocos/realiza-edicao-bloco']) ?>" method="post" class="col-12 mt-3 formBloco">
    <div class="form-group">
        <label for="condominio">Condomínio</label>
        <select class="custom-select" name="id_condominio">
            <option value="">Condominio</option>
            <?php
            foreach (CondominiosController::listaCondominioSelect() as $opcaoCond) { ?>
                <option value="<?= $opcaoCond['id'] ?>" <?= selectedComponent::isSelected($opcaoCond['id'], $edit['id_condominio']) ?>><?= $opcaoCond['nome'] ?></option>
            <?php } ?>
        </select>
    </div>
    <div class="form-group">
        <label for="nomeBloco">Nome do Bloco</label>
        <input type="text" class="form-control" id="nome" name="nome" value="<?= $edit['nome'] ?>" required>
    </div>
    <div class="form-group">
        <label for="numeroAndares">Número de Andares</label>
        <input type="text" class="form-control" id="numeroAndares" name="numeroAndares" value="<?= $edit['numeroAndares'] ?>" required>
    </div>
    <div class="form-group">
        <label for="unidadesPAndar">Unidades por Andar</label>
        <input type="text" class="form-control" id="unidadesPAndar" name="unidadesPAndar" value="<?= $edit['unidadesPAndar'] ?>" required>
    </div>

    <input type="hidden" name="<?= \yii::$app->request->csrfParam ?>" value="<?= \yii::$app->request->csrfToken ?>">
    <input type="hidden" name="id" value="<?= $edit['id'] ?>">
    <div class="row justify-content-between">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
        <button type="submit" class="btn btn-dark buttonEnviar">Enviar</button>
    </div>
</form>

views/blocos/listar-blocos.php
<?

use app\components\modalComponent;
use yii\widgets\LinkPager;
use yii\helpers\Url;
use app\components\alertComponent;
$this->title = "Listar Blocos";
$url_site = Url::base(true);

if(isset($_GET['myAlert'])){
    echo alertComponent::myAlert($_GET['myAlert']['type'],$_GET['myAlert']['msg']);
}
?>
<h1>Blocos</h1>
<div class="row">
    <table class="table col-12 table-responsive-lg mb-5 mt-5 tabelaBlocos">
        <thead>
            <tr>
                <th scope="col">Nome bloco</th>
                <th scope="col">N° Andares</th>
                <th scope="col">Unidades Por Andar</th>
                <th scope="col">Condomínio</th>
                <th scope="col">Data Cad.</th>
                <th><a href="<?= $url_site ?>/index.php?r=blocos%2Fcadastrar-blocos"><button class="btn btn-dark">Adicionar</button></a></th>
            </tr>
        </thead>
        <tbody>
            <?php 
            foreach($blocos as $bloco){ ?>
                <tr data-id="<?= $bloco['id']; ?>" class="bloco">
                    <td><?= $bloco['nome'] ?></td>
                    <td><?= $bloco['numeroAndares'] ?></td>
                    <td><?= $bloco['unidadesPAndar'] ?></td>
                    <td><?= $bloco['nomeCond'] ?></td>
                    <td><?= Yii::$app->formatter->format($bloco['dataCadastro'],'date') ?></td>
                    <td><a class="p-1 removerBloco" href="<?= $url_site ?>/index.php?r=blocos/deleta-bloco&id=<?= $bloco['id']; ?>"><i class="bi bi-x-circle-fill text-danger"></i></a><a class="p-1 openModal" href="<?= $url_site ?>/index.php?r=blocos/editar-bloco&id=<?= $bloco['id']; ?>"><i class="bi bi-pencil-square ml-1 text-info"></i></a></td>
                </tr>
    
            <?php } ?> 
            <tr>
                <td colspan="5">&nbsp;</td>
                <td class="totalRegistros"><?php echo 'Registros: ' . ($paginacao->totalCount<10? '0'. $paginacao->totalCount : $paginacao->totalCount)?></td>
            </tr>
        </tbody>
    </table>
</div>

<?= LinkPager::widget(
    [
        'pagination' => $paginacao,
        'linkContainerOptions' => [
            'class' => 'btn-group'
        ],
        'linkOptions' => [
            'class' => 'btn btn-dark'
        ],
        'disabledListItemSubTagOptions' => [
            'class' => 'btn btn-secondary'
        ]
    ]
    ) ?>
<?= modalComponent::initModal('Edição de Bloco') ?>